Remove duplicate word 'Engineer'
AbdullahAlShaad/AbdullahAlShaad pull request #1
Opened 2023-12-26 11:43 UTC by nurRiyad

2023-12-26 11:45 UTC, ishtiaqhimel approved these changes

2023-12-26 11:50 UTC, tapojit047 requested changes

2023-12-26 11:50 UTC, tapojit047 commented on README.md
> +- 🔭 I’m currently working at [AppsCode](https://www.appscode.com/) as a Software Engineer
"Senior Software Engineer"

2023-12-26 11:59 UTC, ishtiaqhimel approved these changes

2023-12-27 04:03 UTC, tapojit047 approved these changes

2023-12-28 05:24 UTC, AbdullahAlShaad approved these changes
LGTM!

2023-12-28 05:24 UTC, merged